#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_tentacle = env_modules.Clone()
env_tentacle.add_source_files(env.modules_sources, "*.cpp")
env_tentacle.GLSL_HEADER("tentacle.glsl")
env_tentacle.Depends(Glob("*.glsl.gen.h"), ["#glsl_builders.py"])
